/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


import functions.SalvarVeículo;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author mark
 */
public class menuInicial extends javax.swing.JFrame {

    /**
     * Creates new form menuInicial
     */
    public menuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addButtom = new javax.swing.JButton();
        pesqButom = new javax.swing.JButton();
        add = new javax.swing.JLabel();
        add1 = new javax.swing.JLabel();
        sobreButom = new javax.swing.JButton();
        add2 = new javax.swing.JLabel();
        sairButom = new javax.swing.JButton();
        add3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        atualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dados Cadastrados");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 170, 380, 39);

        addButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconnADD.png"))); // NOI18N
        addButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtomActionPerformed(evt);
            }
        });
        getContentPane().add(addButtom);
        addButtom.setBounds(490, 220, 65, 60);

        pesqButom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconnPesquisar.png"))); // NOI18N
        pesqButom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqButomActionPerformed(evt);
            }
        });
        getContentPane().add(pesqButom);
        pesqButom.setBounds(620, 220, 65, 60);

        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setText("add");
        getContentPane().add(add);
        add.setBounds(490, 290, 65, 14);

        add1.setForeground(new java.awt.Color(255, 255, 255));
        add1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add1.setText("pesquisar");
        getContentPane().add(add1);
        add1.setBounds(620, 290, 65, 14);

        sobreButom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconnSobre.png"))); // NOI18N
        sobreButom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreButomActionPerformed(evt);
            }
        });
        getContentPane().add(sobreButom);
        sobreButom.setBounds(490, 310, 65, 60);

        add2.setForeground(new java.awt.Color(255, 255, 255));
        add2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add2.setText("sobre");
        getContentPane().add(add2);
        add2.setBounds(490, 380, 65, 14);

        sairButom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconnSair.png"))); // NOI18N
        sairButom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButomActionPerformed(evt);
            }
        });
        getContentPane().add(sairButom);
        sairButom.setBounds(620, 310, 65, 60);

        add3.setForeground(new java.awt.Color(255, 255, 255));
        add3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add3.setText("sair");
        getContentPane().add(add3);
        add3.setBounds(620, 380, 65, 14);

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu Auxiliar");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51), new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 170, 384, 39);

        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(384, 210, 10, 210);

        atualizar.setText("Mostrar Placas");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar);
        atualizar.setBounds(120, 300, 120, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconnUser.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 20, 120, 110);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Beta 0.0.0.1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 60, 100, 50);

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Controle e Cadastro de Veículos");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 20, 420, 50);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fundoPlanoMenuInicial.jpg"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 840, 430);

        setBounds(0, 0, 806, 466);
    }// </editor-fold>//GEN-END:initComponents

    private void sairButomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButomActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairButomActionPerformed

    private void addButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtomActionPerformed
        // TODO add your handling code here:
        telaAdicionarVeiculo veiculos = new telaAdicionarVeiculo();
        veiculos.setVisible(true);
        dispose();
    }//GEN-LAST:event_addButtomActionPerformed

    private void sobreButomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreButomActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "\tSobre\nAplicação desenvolvida para a obtenção da 3º nota\nda disciplina Linguagem de Programação II.\n\twww.Mark.org.br");

    }//GEN-LAST:event_sobreButomActionPerformed

    private void pesqButomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqButomActionPerformed
        // TODO add your handling code here:
        telaProcurarVeiculo add = new telaProcurarVeiculo();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_pesqButomActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        File file = new File("Total.txt");
	Scanner sc = null;
        String texto = "";
        try {
            sc = new Scanner(file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(menuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

	while (sc.hasNextLine())
	{
		texto += sc.nextLine(); // REPARE QUE ESTOU USANDO O operador:   +=
	}
        JOptionPane.showMessageDialog(this, "Placas\n"+texto);
    }//GEN-LAST:event_atualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JLabel add1;
    private javax.swing.JLabel add2;
    private javax.swing.JLabel add3;
    private javax.swing.JButton addButtom;
    private javax.swing.JButton atualizar;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton pesqButom;
    private javax.swing.JButton sairButom;
    private javax.swing.JButton sobreButom;
    // End of variables declaration//GEN-END:variables
}
