/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import functions.CadastroUsuarios;
import functions.Loguin;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author mark
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        imgIcone = new javax.swing.JLabel();
        textTitulo = new javax.swing.JLabel();
        textSenha = new javax.swing.JLabel();
        textUser = new javax.swing.JLabel();
        inputUserName = new javax.swing.JTextField();
        btLoguin = new javax.swing.JButton();
        inputPassword = new javax.swing.JPasswordField();
        btCadastro = new javax.swing.JButton();
        btMostrarSenha1 = new javax.swing.JButton();
        imgFundo = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgIcone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iconn1.png"))); // NOI18N
        imgIcone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(imgIcone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 100));

        textTitulo.setBackground(new java.awt.Color(204, 204, 204));
        textTitulo.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        textTitulo.setForeground(new java.awt.Color(255, 255, 255));
        textTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo.setText("Controle Central");
        textTitulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(textTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 560, 30));

        textSenha.setBackground(new java.awt.Color(204, 204, 204));
        textSenha.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        textSenha.setForeground(new java.awt.Color(255, 255, 255));
        textSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSenha.setText("Senha");
        textSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 560, 30));

        textUser.setBackground(new java.awt.Color(204, 204, 204));
        textUser.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        textUser.setForeground(new java.awt.Color(255, 255, 255));
        textUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textUser.setText("Usuário");
        textUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(textUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 560, 30));

        inputUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputUserName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(153, 153, 153)));
        inputUserName.setCaretColor(null);
        getContentPane().add(inputUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 210, 30));

        btLoguin.setBackground(new java.awt.Color(0, 102, 0));
        btLoguin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btLoguin.setText("Loguin");
        btLoguin.setBorder(null);
        btLoguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoguinActionPerformed(evt);
            }
        });
        getContentPane().add(btLoguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 110, 30));

        inputPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(153, 153, 153)));
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 210, 30));

        btCadastro.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        btCadastro.setText("Cadastrar");
        btCadastro.setBorder(null);
        btCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 80, 20));

        btMostrarSenha1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btMostrarSenha1.setText("verificar");
        btMostrarSenha1.setBorder(null);
        btMostrarSenha1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMostrarSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarSenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(btMostrarSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 80, 20));

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fundoPlanoLoguin.jpg"))); // NOI18N
        getContentPane().add(imgFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 570, 430));

        setSize(new java.awt.Dimension(587, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void btLoguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoguinActionPerformed
        // TODO add your handling code here:
        try{
           
             int K1, K2;
        Loguin data = new Loguin(inputUserName.getText(), inputPassword.getText());
        K1 = data.mVerificarLoginUser(inputUserName.getText());
        K2 = data.VerificarLoginSenha(inputPassword.getText());
        
        if(K1 == 1 && K2 ==1){
            menuInicial menu = new menuInicial();
            menu.setVisible(true);
            dispose();
        }else
            if(K1 == 0 && K2 == 0){
               JOptionPane.showMessageDialog(data, "|OP|->Erro 002\n Não forma encontrados usuários\ncom esses dados.");
             
            }else
                if(K1 !=0 && K2 ==0){
                    JOptionPane.showMessageDialog(data, "|OP|-> Erro 003.\n Verifique os dados.\nVeja se estão corretos.\n(Ajuda)->Senha Incorreta.");
                }else
                    if(K1 == 0 && K2 != 0){
                        JOptionPane.showMessageDialog(data, "|OP|-> Erro 004.\n Verifique os dados.\nVeja se estão corretos.\n(Ajuda)->Usuário Incorreto.");
                    }
            
        }catch(HeadlessException A){
            System.exit(0);
        }
    }//GEN-LAST:event_btLoguinActionPerformed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        // TODO add your handling code here:
        telaAdicionarUsuario addUser = new telaAdicionarUsuario();
        addUser.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btCadastroActionPerformed

    private void btMostrarSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarSenha1ActionPerformed
        // TODO add your handling code here:
        if(inputUserName.getText().equals("") && !inputPassword.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Veficar Dados\n"+"*Usuário: Não Inserido!"+"\n*Senha: "+inputPassword.getText());
        }else
            if(!inputUserName.getText().equals("") && inputPassword.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Verificar Dados\n*Usuário: "+inputUserName.getText()+"\n*Senha: Não Inserido!");
            }
            else{
                if(!inputUserName.getText().equals("") && !inputPassword.getText().equals("")){
                  JOptionPane.showMessageDialog(this, "Verificar Dados\n *Nome: "+inputUserName.getText()+"\n*Senha: "+inputPassword.getText());
                }
            }
    }//GEN-LAST:event_btMostrarSenha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLogin().setVisible(true);
                new telaLogin().setDefaultCloseOperation(telaLogin.EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btLoguin;
    private javax.swing.JButton btMostrarSenha1;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel imgIcone;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUserName;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel textSenha;
    private javax.swing.JLabel textTitulo;
    private javax.swing.JLabel textUser;
    // End of variables declaration//GEN-END:variables
}
