/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import functions.SalvarVeículo;

/**
 *
 * @author mark
 */
public class telaProcurarVeiculo extends javax.swing.JFrame {

    /**
     * Creates new form telaAdicionarVeiculo
     */
    public telaProcurarVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabelaCentral = new javax.swing.JTabbedPane();
        pesquisa = new javax.swing.JPanel();
        btSalvar1 = new javax.swing.JButton();
        PLACA = new javax.swing.JFormattedTextField();
        Texto1 = new javax.swing.JLabel();
        addMotos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nomeResut = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        veiculoResut = new javax.swing.JTextField();
        rgResut = new javax.swing.JTextField();
        foneResut = new javax.swing.JTextField();
        cpfResut = new javax.swing.JTextField();
        dataResut = new javax.swing.JTextField();
        placaResut = new javax.swing.JTextField();
        codRestut = new javax.swing.JTextField();
        horaResut = new javax.swing.JTextField();
        tipoResult = new javax.swing.JTextField();
        planodeFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Veículos");
        setResizable(false);
        getContentPane().setLayout(null);

        TabelaCentral.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)), "Resultado da Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        pesquisa.setBackground(new java.awt.Color(255, 255, 255));

        btSalvar1.setBackground(new java.awt.Color(153, 153, 153));
        btSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/inconnSearch.png"))); // NOI18N
        btSalvar1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white), "Procurar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        btSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar1ActionPerformed(evt);
            }
        });

        PLACA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.lightGray), "PLACA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));
        try {
            PLACA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***-****")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        PLACA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PLACA.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        PLACA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLACAActionPerformed(evt);
            }
        });

        Texto1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Texto1.setText("Digite a placa do veículo para realizar a busca");

        javax.swing.GroupLayout pesquisaLayout = new javax.swing.GroupLayout(pesquisa);
        pesquisa.setLayout(pesquisaLayout);
        pesquisaLayout.setHorizontalGroup(
            pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisaLayout.createSequentialGroup()
                        .addComponent(btSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisaLayout.createSequentialGroup()
                        .addComponent(PLACA, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
            .addGroup(pesquisaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        pesquisaLayout.setVerticalGroup(
            pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pesquisaLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(Texto1)
                .addGap(34, 34, 34)
                .addComponent(PLACA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSalvar1)
                .addGap(42, 42, 42))
        );

        TabelaCentral.addTab("Pesquisar Veículos", pesquisa);

        addMotos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        addMotos.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COD");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HORA");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PLACA");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nome do Proprietário");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VEÍCULO");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TIPO");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CPF");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("GR");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CPF");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        nomeResut.setEditable(false);
        nomeResut.setBackground(new java.awt.Color(255, 255, 255));
        nomeResut.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        nomeResut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeResut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeResutActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("FONE");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));

        veiculoResut.setEditable(false);
        veiculoResut.setBackground(new java.awt.Color(255, 255, 255));
        veiculoResut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        veiculoResut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        veiculoResut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoResutActionPerformed(evt);
            }
        });

        rgResut.setEditable(false);
        rgResut.setBackground(new java.awt.Color(255, 255, 255));
        rgResut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        rgResut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rgResut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgResutActionPerformed(evt);
            }
        });

        foneResut.setEditable(false);
        foneResut.setBackground(new java.awt.Color(255, 255, 255));
        foneResut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        foneResut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        foneResut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foneResutActionPerformed(evt);
            }
        });

        cpfResut.setEditable(false);
        cpfResut.setBackground(new java.awt.Color(255, 255, 255));
        cpfResut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        cpfResut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpfResut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfResutActionPerformed(evt);
            }
        });

        dataResut.setEditable(false);
        dataResut.setBackground(new java.awt.Color(255, 255, 255));
        dataResut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        dataResut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataResut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataResutActionPerformed(evt);
            }
        });

        placaResut.setEditable(false);
        placaResut.setBackground(new java.awt.Color(255, 255, 255));
        placaResut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        placaResut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        placaResut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaResutActionPerformed(evt);
            }
        });

        codRestut.setEditable(false);
        codRestut.setBackground(new java.awt.Color(255, 255, 255));
        codRestut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        codRestut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codRestut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codRestutActionPerformed(evt);
            }
        });

        horaResut.setEditable(false);
        horaResut.setBackground(new java.awt.Color(255, 255, 255));
        horaResut.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        horaResut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horaResut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaResutActionPerformed(evt);
            }
        });

        tipoResult.setEditable(false);
        tipoResult.setBackground(new java.awt.Color(255, 255, 255));
        tipoResult.setFont(new java.awt.Font("Yu Gothic Medium", 0, 11)); // NOI18N
        tipoResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipoResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addMotosLayout = new javax.swing.GroupLayout(addMotos);
        addMotos.setLayout(addMotosLayout);
        addMotosLayout.setHorizontalGroup(
            addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMotosLayout.createSequentialGroup()
                .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMotosLayout.createSequentialGroup()
                        .addGap(559, 559, 559)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addMotosLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(addMotosLayout.createSequentialGroup()
                                    .addComponent(codRestut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(placaResut, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addMotosLayout.createSequentialGroup()
                                    .addComponent(horaResut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dataResut, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(veiculoResut, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(addMotosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addMotosLayout.createSequentialGroup()
                                    .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addMotosLayout.createSequentialGroup()
                                            .addComponent(foneResut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cpfResut, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(33, 33, 33)
                                    .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(rgResut)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                                .addGroup(addMotosLayout.createSequentialGroup()
                                    .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nomeResut)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                                    .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addMotosLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(addMotosLayout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(tipoResult))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMotosLayout.setVerticalGroup(
            addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMotosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(placaResut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codRestut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoResut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataResut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaResut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMotosLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel10))
                    .addGroup(addMotosLayout.createSequentialGroup()
                        .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addMotosLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(nomeResut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addMotosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(addMotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rgResut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foneResut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfResut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        TabelaCentral.addTab("Dados Obtidos", addMotos);

        getContentPane().add(TabelaCentral);
        TabelaCentral.setBounds(90, 50, 500, 360);

        planodeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fudoPlanoTeste.jpg"))); // NOI18N
        getContentPane().add(planodeFundo);
        planodeFundo.setBounds(-6, -20, 1040, 570);

        jMenu1.setText("Opções");

        jMenuItem1.setText("Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Fechar Aplicação");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(704, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        menuInicial menu = new menuInicial();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar1ActionPerformed
        // TODO add your handling code here:
        
         String Cod = codRestut.getText();
         String Placa = placaResut.getText();
         String Hora = horaResut.getText();
         String Data = dataResut.getText();
         String Veiculo = veiculoResut.getText();
         String Nome = nomeResut.getText();
         String Fone = foneResut.getText();
         String Cpf = cpfResut.getText();
         String Rg = rgResut.getText();
         String Tipo = tipoResult.getText();
         String NomeArq = PLACA.getText();
         SalvarVeículo data = new SalvarVeículo(Cod, Placa, Hora, Data, Veiculo, Nome, Fone, Cpf, Rg, Tipo);
         
        String linha= data.mostrarDados(NomeArq, Cod, Placa, Hora, Data, Veiculo, Nome, Fone, Cpf, Rg, Tipo);
        String dados[] = linha.split(";");
           codRestut.setText(dados[0]);
           placaResut.setText(dados[1]);
           horaResut.setText(dados[2]);
           dataResut.setText(dados[3]);
           veiculoResut.setText(dados[4]);
           nomeResut.setText(dados[5]);
           tipoResult.setText("NULL");
           foneResut.setText(dados[7]);
           cpfResut.setText(dados[8]);
           rgResut.setText(dados[9]);
        Texto1.setText("Dados obtidos!Selecione a opção :Dados Obtidos.");
    }//GEN-LAST:event_btSalvar1ActionPerformed

    private void PLACAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLACAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PLACAActionPerformed

    private void veiculoResutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoResutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoResutActionPerformed

    private void nomeResutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeResutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeResutActionPerformed

    private void rgResutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgResutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgResutActionPerformed

    private void foneResutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foneResutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foneResutActionPerformed

    private void cpfResutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfResutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfResutActionPerformed

    private void dataResutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataResutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataResutActionPerformed

    private void placaResutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaResutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaResutActionPerformed

    private void codRestutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codRestutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codRestutActionPerformed

    private void horaResutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaResutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaResutActionPerformed

    private void tipoResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaProcurarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaProcurarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaProcurarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaProcurarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaProcurarVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField PLACA;
    private javax.swing.JTabbedPane TabelaCentral;
    private javax.swing.JLabel Texto1;
    private javax.swing.JPanel addMotos;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JTextField codRestut;
    private javax.swing.JTextField cpfResut;
    private javax.swing.JTextField dataResut;
    private javax.swing.JTextField foneResut;
    private javax.swing.JTextField horaResut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField nomeResut;
    private javax.swing.JPanel pesquisa;
    private javax.swing.JTextField placaResut;
    private javax.swing.JLabel planodeFundo;
    private javax.swing.JTextField rgResut;
    private javax.swing.JTextField tipoResult;
    private javax.swing.JTextField veiculoResut;
    // End of variables declaration//GEN-END:variables
}
